module.exports = {
    ErrorCode: {
        ethereum: {
            SUCCESS: 0,
            INTERFACE_ERROR: 1,
            DATA_FORMAT_ERROR: 2,
            ABI_ENCODE_ERROR: 3,
            SEND_TRANSACTION_ERROR: 4,
            GET_TARGET_ERROR: 5,
            DECODE_DATA_ERROR: 6,
            CONVERT_TO_JSON_ERROR: 7,
            MESSAGE_AGGREGATED: 8,
            GET_SENT_MESSAGE_ERROR: 9,
            ENCODE_DATA_ERROR: 10,
            MESSAGE_FORMAT_ERROR: 11,
        },
    },
    
    MsgType: {
        String: 0n,
        U8: 1n,
        U16: 2n,
        U32: 3n,
        U64: 4n,
        U128: 5n,
        I8: 6n,
        I16: 7n,
        I32: 8n,
        I64: 9n,
        I128: 10n,
        StringArray: 11n,
        U8Array: 12n,
        U16Array: 13n,
        U32Array: 14n,
        U64Array: 15n,
        U128Array: 16n,
        I8Array: 17n,
        I16Array: 18n,
        I32Array: 19n,
        I64Array: 20n,
        I128Array: 21n,
        Bytes: 22n,
        MAX: 23n,
    },

    SQoSType: {
        Reveal: 0,
        Challenge: 1,
        Threshold: 2,
        Priority: 3,
        ExceptionRollback: 4,
        SelectionDelay: 5,
        Anonymous: 6,
        Identity: 7,
        Isolation: 8,
        CrossVerify: 9,
        MAX: 10,
    }
}